import pandas as pd
import numpy as np
from src.utils.config import DATA_RAW


def build_2026_prospects() -> pd.DataFrame:
    """
    2026 NFL Draft prospect list with college stats and measurables.
    Sources: public mock drafts, college stats from sports-reference.
    Updated: Feb 2026
    """

    prospects = [
        # ── QBs ─────────────────────────────────────────
        {
            "player": "Shedeur Sanders",
            "pos": "QB",
            "college": "Colorado",
            "age": 22,
            "ht": "6-2",
            "wt": 215,
            "forty": None,
            "round": 1,
            "pick": 3,
            "college_pass_att": 1399,
            "college_pass_yd": 10296,
            "college_pass_td": 72,
            "college_int": 18,
            "college_rush_att": 136,
            "college_rush_yd": 157,
            "college_rush_td": 6,
        },
        {
            "player": "Cam Ward",
            "pos": "QB",
            "college": "Miami",
            "age": 23,
            "ht": "6-2",
            "wt": 223,
            "forty": None,
            "round": 1,
            "pick": 1,
            "college_pass_att": 1915,
            "college_pass_yd": 16593,
            "college_pass_td": 130,
            "college_int": 39,
            "college_rush_att": 303,
            "college_rush_yd": 885,
            "college_rush_td": 16,
        },
        {
            "player": "Jalen Milroe",
            "pos": "QB",
            "college": "Alabama",
            "age": 22,
            "ht": "6-2",
            "wt": 225,
            "forty": None,
            "round": 1,
            "pick": 8,
            "college_pass_att": 800,
            "college_pass_yd": 6009,
            "college_pass_td": 47,
            "college_int": 12,
            "college_rush_att": 302,
            "college_rush_yd": 1499,
            "college_rush_td": 24,
        },
        {
            "player": "Quinn Ewers",
            "pos": "QB",
            "college": "Texas",
            "age": 22,
            "ht": "6-2",
            "wt": 210,
            "forty": None,
            "round": 1,
            "pick": 15,
            "college_pass_att": 1071,
            "college_pass_yd": 8091,
            "college_pass_td": 56,
            "college_int": 21,
            "college_rush_att": 110,
            "college_rush_yd": 179,
            "college_rush_td": 8,
        },
        {
            "player": "Jaxson Dart",
            "pos": "QB",
            "college": "Ole Miss",
            "age": 22,
            "ht": "6-1",
            "wt": 225,
            "forty": None,
            "round": 2,
            "pick": 35,
            "college_pass_att": 1436,
            "college_pass_yd": 11480,
            "college_pass_td": 81,
            "college_int": 22,
            "college_rush_att": 237,
            "college_rush_yd": 538,
            "college_rush_td": 11,
        },

        # ── RBs ─────────────────────────────────────────
        {
            "player": "Ashton Jeanty",
            "pos": "RB",
            "college": "Boise State",
            "age": 21,
            "ht": "5-9",
            "wt": 215,
            "forty": None,
            "round": 1,
            "pick": 5,
            "college_rush_att": 688,
            "college_rush_yd": 4769,
            "college_rush_td": 52,
            "college_rec": 64,
            "college_rec_yd": 671,
            "college_rec_td": 3,
        },
        {
            "player": "Omarion Hampton",
            "pos": "RB",
            "college": "North Carolina",
            "age": 21,
            "ht": "6-0",
            "wt": 220,
            "forty": None,
            "round": 1,
            "pick": 20,
            "college_rush_att": 716,
            "college_rush_yd": 3779,
            "college_rush_td": 36,
            "college_rec": 63,
            "college_rec_yd": 551,
            "college_rec_td": 2,
        },
        {
            "player": "Kaleb Johnson",
            "pos": "RB",
            "college": "Iowa",
            "age": 21,
            "ht": "6-0",
            "wt": 225,
            "forty": None,
            "round": 2,
            "pick": 40,
            "college_rush_att": 557,
            "college_rush_yd": 3325,
            "college_rush_td": 31,
            "college_rec": 34,
            "college_rec_yd": 313,
            "college_rec_td": 0,
        },
        {
            "player": "RJ Harvey",
            "pos": "RB",
            "college": "UCF",
            "age": 23,
            "ht": "5-11",
            "wt": 210,
            "forty": None,
            "round": 2,
            "pick": 55,
            "college_rush_att": 730,
            "college_rush_yd": 4520,
            "college_rush_td": 51,
            "college_rec": 73,
            "college_rec_yd": 712,
            "college_rec_td": 5,
        },
        {
            "player": "Devin Neal",
            "pos": "RB",
            "college": "Kansas",
            "age": 22,
            "ht": "5-11",
            "wt": 210,
            "forty": None,
            "round": 3,
            "pick": 80,
            "college_rush_att": 861,
            "college_rush_yd": 4487,
            "college_rush_td": 40,
            "college_rec": 83,
            "college_rec_yd": 739,
            "college_rec_td": 3,
        },

        # ── WRs ─────────────────────────────────────────
        {
            "player": "Tetairoa McMillan",
            "pos": "WR",
            "college": "Arizona",
            "age": 21,
            "ht": "6-5",
            "wt": 212,
            "forty": None,
            "round": 1,
            "pick": 7,
            "college_rec": 210,
            "college_rec_yd": 3423,
            "college_rec_td": 24,
            "college_rush_att": 3,
            "college_rush_yd": 12,
        },
        {
            "player": "Travis Hunter",
            "pos": "WR",
            "college": "Colorado",
            "age": 21,
            "ht": "6-1",
            "wt": 185,
            "forty": None,
            "round": 1,
            "pick": 2,
            "college_rec": 178,
            "college_rec_yd": 2619,
            "college_rec_td": 21,
            "college_rush_att": 5,
            "college_rush_yd": 11,
        },
        {
            "player": "Luther Burden III",
            "pos": "WR",
            "college": "Missouri",
            "age": 21,
            "ht": "5-11",
            "wt": 208,
            "forty": None,
            "round": 1,
            "pick": 12,
            "college_rec": 212,
            "college_rec_yd": 2736,
            "college_rec_td": 24,
            "college_rush_att": 30,
            "college_rush_yd": 145,
        },
        {
            "player": "Emeka Egbuka",
            "pos": "WR",
            "college": "Ohio State",
            "age": 22,
            "ht": "6-1",
            "wt": 206,
            "forty": None,
            "round": 1,
            "pick": 18,
            "college_rec": 207,
            "college_rec_yd": 2834,
            "college_rec_td": 24,
            "college_rush_att": 22,
            "college_rush_yd": 120,
        },
        {
            "player": "Isaiah Bond",
            "pos": "WR",
            "college": "Texas",
            "age": 21,
            "ht": "6-0",
            "wt": 190,
            "forty": None,
            "round": 1,
            "pick": 25,
            "college_rec": 131,
            "college_rec_yd": 1950,
            "college_rec_td": 17,
            "college_rush_att": 10,
            "college_rush_yd": 75,
        },
        {
            "player": "Tre Harris",
            "pos": "WR",
            "college": "Ole Miss",
            "age": 24,
            "ht": "6-3",
            "wt": 205,
            "forty": None,
            "round": 1,
            "pick": 22,
            "college_rec": 146,
            "college_rec_yd": 2413,
            "college_rec_td": 13,
            "college_rush_att": 2,
            "college_rush_yd": 5,
        },

        # ── TEs ─────────────────────────────────────────
        {
            "player": "Tyler Warren",
            "pos": "TE",
            "college": "Penn State",
            "age": 23,
            "ht": "6-6",
            "wt": 260,
            "forty": None,
            "round": 1,
            "pick": 10,
            "college_rec": 133,
            "college_rec_yd": 1560,
            "college_rec_td": 14,
        },
        {
            "player": "Colston Loveland",
            "pos": "TE",
            "college": "Michigan",
            "age": 21,
            "ht": "6-5",
            "wt": 245,
            "forty": None,
            "round": 1,
            "pick": 28,
            "college_rec": 110,
            "college_rec_yd": 1326,
            "college_rec_td": 12,
        },
        {
            "player": "Mason Taylor",
            "pos": "TE",
            "college": "LSU",
            "age": 22,
            "ht": "6-5",
            "wt": 252,
            "forty": None,
            "round": 2,
            "pick": 45,
            "college_rec": 130,
            "college_rec_yd": 1261,
            "college_rec_td": 8,
        },
        {
            "player": "Gunnar Helm",
            "pos": "TE",
            "college": "Texas",
            "age": 22,
            "ht": "6-4",
            "wt": 245,
            "forty": None,
            "round": 2,
            "pick": 50,
            "college_rec": 120,
            "college_rec_yd": 1458,
            "college_rec_td": 10,
        },
    ]

    df = pd.DataFrame(prospects)

    print(f"2026 Prospects: {len(df)}")
    print(df["pos"].value_counts())
    print(f"\n{df[['player', 'pos', 'college', 'pick']].to_string(index=False)}")

    return df


def save(df: pd.DataFrame) -> None:
    path = DATA_RAW / "prospects_2026.csv"
    df.to_csv(path, index=False)
    print(f"\nSaved to {path}")


def run():
    df = build_2026_prospects()
    save(df)
    return df


if __name__ == "__main__":
    run()